[versions]
activityKtx = "1.10.1"
agp = "8.8.2"
appcompat = "1.7.0"
circleimageview = "3.1.0"
constraintlayout = "2.2.1"
coreKtx = "1.15.0"
glide = "4.16.0"
material = "1.12.0"
navigationKtx = "2.8.9"
playServicesAuth = "21.3.0"

# 🔹 Firebase
firebaseBom = "33.10.0"
firebaseAuth = "23.2.0"
firebaseFirestore = "25.1.3"
firebaseStorage = "21.0.1"
firebaseMessaging = "24.1.1"

# 🔹 Testing
junit = "4.13.2"
androidxJunit = "1.2.1"
espressoCore = "3.6.1"

# 🔹 Otras Librerías
picasso = "2.8"
kotlin = "2.1.10"

[libraries]
# 🔹 AndroidX
androidx-activity-ktx = { module = "androidx.activity:activity-ktx", version.ref = "activityKtx" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }

circleimageview = { module = "de.hdodenhof:circleimageview", version.ref = "circleimageview" }
glide = { module = "com.github.bumptech.glide:glide", version.ref = "glide" }
ksp = { module = "com.github.bumptech.glide:ksp", version.ref = "glide" }
material = { module = "com.google.android.material:material", version.ref = "material" }
androidx-navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navigationKtx" }
androidx-navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navigationKtx" }
play-services-auth = { module = "com.google.android.gms:play-services-auth", version.ref = "playServicesAuth" }

# 🔹 Firebase
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-auth-ktx = { module = "com.google.firebase:firebase-auth-ktx", version.ref = "firebaseAuth" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestore" }
firebase-storage-ktx = { module = "com.google.firebase:firebase-storage-ktx", version.ref = "firebaseStorage" }
firebase-messaging-ktx = { module = "com.google.firebase:firebase-messaging-ktx", version.ref = "firebaseMessaging" }

picasso = { module = "com.squareup.picasso:picasso", version.ref = "picasso" }

junit = { module = "junit:junit", version.ref = "junit" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidxJunit" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
